-- ========================================================================
-- Vizio Snowflake Intelligence Setup - Step 0: Base Tables
-- Creates the source database structure and tables for demo accounts
-- ========================================================================
--
-- Customer: Vizio, Inc.
-- Purpose: Replicate Vizio source table structure for demo/testing
-- Generated: 2026-09-30
--
-- IMPORTANT: Run this script BEFORE 00_infrastructure_vizio.sql
--            when deploying to a demo account without existing source data
--
-- This script creates:
--   - VIZIO_STREAMING database (WatchFree+ live/AVOD, revenue)
--   - VIZIO_DEVICES database (TV fleet, homescreen, apps, OEM)
--   - VIZIO_REVENUE database (ad revenue, TV sales, accounts)
--   - VIZIO_ENGAGEMENT database (active accounts, churn, retention)
--   - VIZIO_MARKETING database (impressions, sports, push notifications)
-- ========================================================================

USE ROLE accountadmin;

-- ========================================================================
-- CREATE SOURCE DATABASES
-- ========================================================================

CREATE DATABASE IF NOT EXISTS VIZIO_STREAMING;
CREATE SCHEMA IF NOT EXISTS VIZIO_STREAMING.WFP;

CREATE DATABASE IF NOT EXISTS VIZIO_DEVICES;
CREATE SCHEMA IF NOT EXISTS VIZIO_DEVICES.FLEET;
CREATE SCHEMA IF NOT EXISTS VIZIO_DEVICES.ENGAGEMENT;
CREATE SCHEMA IF NOT EXISTS VIZIO_DEVICES.APPS;
CREATE SCHEMA IF NOT EXISTS VIZIO_DEVICES.OEM;

CREATE DATABASE IF NOT EXISTS VIZIO_REVENUE;
CREATE SCHEMA IF NOT EXISTS VIZIO_REVENUE.ADS;
CREATE SCHEMA IF NOT EXISTS VIZIO_REVENUE.HARDWARE;
CREATE SCHEMA IF NOT EXISTS VIZIO_REVENUE.ACCOUNTS;

CREATE DATABASE IF NOT EXISTS VIZIO_ENGAGEMENT;
CREATE SCHEMA IF NOT EXISTS VIZIO_ENGAGEMENT.KPIS;
CREATE SCHEMA IF NOT EXISTS VIZIO_ENGAGEMENT.RETENTION;

CREATE DATABASE IF NOT EXISTS VIZIO_MARKETING;
CREATE SCHEMA IF NOT EXISTS VIZIO_MARKETING.HOMESCREEN;
CREATE SCHEMA IF NOT EXISTS VIZIO_MARKETING.SPORTS;
CREATE SCHEMA IF NOT EXISTS VIZIO_MARKETING.BRAZE;
CREATE SCHEMA IF NOT EXISTS VIZIO_MARKETING.INSCAPE;

-- ========================================================================
-- TABLE 1: WFP Live Channel Summary
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_STREAMING.WFP.AGG_WFP_LIVE_CHANNEL_SUMMARY_WITH_CHANNEL_NAMES (
    TIME_GRAIN VARCHAR(20),
    DATE DATE,
    CHANNEL_SESSION_LENGTH NUMBER(18,2),
    OS_VERSION VARCHAR(100),
    OEM_BRAND VARCHAR(100),
    BACKEND_APP_TYPE VARCHAR(100),
    CHANNEL_TYPE VARCHAR(100),
    AIRINGS_KEY VARCHAR(200),
    EPG_CHANNEL_NAME VARCHAR(500),
    IS_OTA BOOLEAN,
    EPG_CHANNEL_CATEGORY VARCHAR(200),
    EPG_CHANNEL_CATEGORY_ID VARCHAR(50),
    AFFILIATES VARCHAR(500)
);

-- ========================================================================
-- TABLE 2: WFP AVOD Content Summary
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_STREAMING.WFP.AGG_WFP_AVOD_CONTENT_SUMMARY_WITH_METADATA_V2 (
    TIME_GRAIN VARCHAR(20),
    DATE DATE,
    PLAYER_TYPE VARCHAR(100),
    OS_VERSION VARCHAR(100),
    MEDIA_ID VARCHAR(100),
    CONTENT_TITLE VARCHAR(1000),
    EPISODE_TITLE VARCHAR(1000),
    SEASON_EPISODE VARCHAR(100),
    PRODUCTION_TYPE VARCHAR(100),
    GENRE VARCHAR(200),
    STUDIO VARCHAR(500),
    SERIES_NAME VARCHAR(500),
    PUBLISH_DATE DATE,
    RATING VARCHAR(50),
    LANGUAGE VARCHAR(50),
    DEVICES NUMBER(18,0),
    DURATION_MINS NUMBER(18,2),
    AVOD_SESSIONS NUMBER(18,0),
    SESSION_DURATION_PER_AVOD_SESSION NUMBER(18,2),
    SESSION_DURATION_PER_TOKEN NUMBER(18,2),
    LAUNCHES NUMBER(18,0),
    SESSION_LENGTH NUMBER(18,2),
    OEM_BRAND VARCHAR(100),
    BACKEND_APP_TYPE VARCHAR(100)
);

-- ========================================================================
-- TABLE 3: WFP Global KPIs Rolling 30 Day
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_STREAMING.WFP.AGG_WFP_GLOBAL_KPIS_ROLLING_30_DAY (
    DATE DATE,
    WFP_TOKENS NUMBER(18,0),
    AVOD_TOKENS NUMBER(18,0),
    WFP_AND_AVOD_TOKENS NUMBER(18,0),
    WFP_SESSIONS NUMBER(18,0),
    AVOD_SESSIONS NUMBER(18,0),
    WFP_AND_AVOD_SESSIONS NUMBER(18,0),
    WFP_VIEWING_HOURS NUMBER(18,2),
    WFP_APP_HOURS NUMBER(18,2),
    AVOD_VIEWING_HOURS NUMBER(18,2),
    WFP_AND_AVOD_VIEWING_HOURS NUMBER(18,2),
    WFP_AND_AVOD_APP_HOURS NUMBER(18,2),
    BACKEND_APP_TYPE VARCHAR(100)
);

-- ========================================================================
-- TABLE 4: WFP Revenue Rolling 30 Days
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_STREAMING.WFP.AGG_WFP_LIVE_AND_AVOD_REVENUE_ROLLING_30_DAYS (
    EVENT_DATE DATE,
    WFP_LIVE_REVENUE NUMBER(18,2),
    WFP_AVOD_REVENUE NUMBER(18,2)
);

-- ========================================================================
-- TABLE 5: WFP AVOD Studio Summary
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_STREAMING.WFP.AGG_WFP_AVOD_STUDIO_SUMMARY (
    TIME_GRAIN VARCHAR(20),
    DATE DATE,
    STUDIO VARCHAR(500),
    DEVICES NUMBER(18,0),
    AVOD_SESSIONS NUMBER(18,0),
    DURATION_MINS NUMBER(18,2),
    LAUNCHES NUMBER(18,0)
);

-- ========================================================================
-- TABLE 6: TV Attributes Current
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_DEVICES.FLEET.AGG_TV_ATTRIBUTE_CURRENT_MV (
    ESN VARCHAR(100),
    DIID VARCHAR(100),
    SOC VARCHAR(50),
    CHIPSET VARCHAR(50),
    MODEL_NAME VARCHAR(200),
    RJ45_MAC VARCHAR(50),
    FIRMWARE VARCHAR(200),
    SERIES VARCHAR(100),
    SIZE VARCHAR(20),
    TOKEN VARCHAR(200),
    OEM_BRAND VARCHAR(100),
    VIEWING VARCHAR(50),
    IP_ADDRESS VARCHAR(50),
    VERSION_SCPL VARCHAR(100),
    CONFIG VARCHAR(200),
    BINARY_ACR VARCHAR(20),
    BINARY_AIRPLAY VARCHAR(20),
    BINARY_APPLETV VARCHAR(20),
    BINARY_BLUETOOTH VARCHAR(20),
    BINARY_COBALT VARCHAR(20),
    BINARY_CONJURE VARCHAR(20),
    BINARY_DAI VARCHAR(20),
    BINARY_VIZIOOS VARCHAR(20),
    BINARY_VIZIONDK VARCHAR(20),
    BINARY_SCPL VARCHAR(20),
    RETAILER_CODE VARCHAR(50),
    RETAILER_NAME VARCHAR(200),
    DNDELIVERYCUSTOMERCOMPLETED VARCHAR(50),
    OS_VERSION VARCHAR(100)
);

-- ========================================================================
-- TABLE 7: Homescreen Summary with TV Attributes
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_DEVICES.ENGAGEMENT.AGG_HOMESCREEN_SUMMARY_WITH_TV_ATTRIBUTES (
    TIME_GRAIN VARCHAR(20),
    DATE DATE,
    CLIENTTYPE VARCHAR(100),
    SOC VARCHAR(50),
    CHIPSET VARCHAR(50),
    MODEL_NAME VARCHAR(200),
    SERIES VARCHAR(100),
    SIZE VARCHAR(20),
    LAUNCH_YEAR INTEGER,
    DEVICES NUMBER(18,0),
    VIEWING_MINUTES NUMBER(18,2),
    AVG_VIEWING_MINUTES NUMBER(18,2),
    MEDIAN_VIEWING_MINUTES NUMBER(18,2),
    OEM_BRAND VARCHAR(100)
);

-- ========================================================================
-- TABLE 8: Homescreen NRC with TV Attributes
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_DEVICES.ENGAGEMENT.AGG_HOMESCREEN_NRC_WITH_TV_ATTRIBUTES (
    MONTH DATE,
    SOC VARCHAR(50),
    CHIPSET VARCHAR(50),
    MODEL_NAME VARCHAR(200),
    SERIES VARCHAR(100),
    SIZE VARCHAR(20),
    LAUNCH_YEAR INTEGER,
    DISPLAY_TECHNOLOGY VARCHAR(100),
    ACTIVE_DEVICES NUMBER(18,0),
    NEW_DEVICES NUMBER(18,0),
    RECURRING_DEVICES NUMBER(18,0),
    RETURNING_DEVICES NUMBER(18,0),
    CHURN_1M_DEVICES NUMBER(18,0),
    CHURN_6M_DEVICES NUMBER(18,0),
    ACTIVE_VIEWING_MINUTES NUMBER(18,2),
    NEW_VIEWING_MINUTES NUMBER(18,2),
    RECURRING_VIEWING_MINUTES NUMBER(18,2),
    RETURNING_VIEWING_MINUTES NUMBER(18,2),
    PREVIOUS_MONTH_ACTIVE NUMBER(18,0),
    GROSS_CHURN_RATE1M NUMBER(18,6),
    RETURN_RATE NUMBER(18,6),
    NET_CHURN1M NUMBER(18,6),
    OEM_BRAND VARCHAR(100)
);

-- ========================================================================
-- TABLE 9: App Devices Launches Sources
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_DEVICES.APPS.AGG_APP_DEVICES_LAUNCHES_SOURCES (
    TIME_GRAIN VARCHAR(20),
    ACTIVITY_DATE DATE,
    CLIENTTYPE VARCHAR(100),
    SOURCE VARCHAR(200),
    APP VARCHAR(500),
    SOC VARCHAR(50),
    CHIPSET VARCHAR(50),
    MODEL_NAME VARCHAR(200),
    SERIES VARCHAR(100),
    SIZE VARCHAR(20),
    VOD_TYPE VARCHAR(100),
    MONETIZATION_TYPE VARCHAR(100),
    DEVICES NUMBER(18,0),
    LAUNCHES NUMBER(18,0),
    OEM_BRAND VARCHAR(100)
);

-- ========================================================================
-- TABLE 10: OEM Launch Devices Cumulative
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_DEVICES.OEM.AGG_OEM_LAUNCH_DEVICES_CUMULATIVE (
    ACTIVITY_DATE DATE,
    OEM_BRAND VARCHAR(100),
    SCTV_NEW_USERS NUMBER(18,0),
    WFP_NEW_USERS NUMBER(18,0),
    AVOD_NEW_USERS NUMBER(18,0),
    AUDIT_UPDATE_TS TIMESTAMP_NTZ,
    MODEL VARCHAR(200)
);

-- ========================================================================
-- TABLE 11: App Metadata (Lookup)
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_DEVICES.APPS.MAPPING_APP_METADATA (
    CURATED_APP_NAME VARCHAR(500),
    ALIAS_APP_NAME VARCHAR(500),
    APP_ID VARCHAR(100),
    NAME_SPACE VARCHAR(200),
    VOD_TYPE VARCHAR(100),
    MONETIZATION_TYPE VARCHAR(100),
    DEPRECATED BOOLEAN,
    IR_CODE VARCHAR(50),
    CURRENT_ROW BOOLEAN,
    LAUNCH_DATE DATE,
    EFFECTIVE_DATE DATE,
    END_DATE DATE
);

-- ========================================================================
-- TABLE 12: Total Video Revenue Time Grain
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_REVENUE.ADS.TOTAL_VIDEO_REVENUE_TIME_GRAIN (
    DATE_PERIOD DATE,
    PRODUCT_LINE VARCHAR(200),
    SALE_TYPE VARCHAR(100),
    TIME_GRAIN VARCHAR(20),
    NET_REVENUE NUMBER(18,2),
    TOTAL_IMPRESSIONS NUMBER(18,0),
    AUDIT_UPDATE_TS TIMESTAMP_NTZ
);

-- ========================================================================
-- TABLE 13: TV Daily Sold Net
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_REVENUE.HARDWARE.AGG_IT_AZURE_DAILY_SOLD_NET_MV (
    SALE_DATE DATE,
    PRODUCT_ERP_ID VARCHAR(100),
    CUSTOMER_ERP_ID VARCHAR(100),
    FK_DATE_KEY INTEGER,
    SUPPLIER_GROUP VARCHAR(200),
    CHIPSET VARCHAR(100),
    SIZE VARCHAR(20),
    CUSTOMER_GROUP VARCHAR(200),
    CATEGORY VARCHAR(200),
    SERIES VARCHAR(100),
    VIDEO_SMART_PLATFORM VARCHAR(100),
    GROSS_SOLD_UNITS NUMBER(18,0),
    ROLLING_GROSS_SOLD_UNITS_30DAYS NUMBER(18,0),
    NET_SOLD_UNITS NUMBER(18,0),
    ROLLING_NET_SOLD_UNITS_30DAYS NUMBER(18,0),
    SHIPPED_UNITS NUMBER(18,0),
    ROLLING_SHIPPED_UNITS_30DAYS NUMBER(18,0),
    AVG_SALE_PRICE NUMBER(18,2),
    AUDIT_UPDATE_TS TIMESTAMP_NTZ,
    INPUT_FILE_NAME VARCHAR(500)
);

-- ========================================================================
-- TABLE 14: Vizio Account Transacted Accounts
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_REVENUE.ACCOUNTS.AGG_VA_TRANSACTED_ACCOUNTS_FULL (
    TIME_GRAIN VARCHAR(20),
    DATE DATE,
    ALL_TRANSACTED_ACCOUNTS NUMBER(18,0),
    SVOD_TRANSACTED_ACCOUNTS NUMBER(18,0),
    TVOD_TRANSACTED_ACCOUNTS NUMBER(18,0)
);

-- ========================================================================
-- TABLE 15: Executive Dashboard
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_ENGAGEMENT.KPIS.AGG_VIZIO_ACCOUNT_EXEC_DASH_V1 (
    PROCESS_DATE DATE,
    ROLLING_30_UNIQUE_ACTIVE_ACCOUNTS NUMBER(18,0),
    ROLLING_30_SVOD_ACTIVE_ACCOUNTS NUMBER(18,0),
    ROLLING_30_DISTINCT_TVOD_ACTIVE_ACCOUNTS NUMBER(18,0),
    ROLLING_30_TVOD_TRANSACTION_COUNT NUMBER(18,0),
    ROLLING_30_SVOD_SUBSCRIPTION_COUNT NUMBER(18,0),
    ROLLING_30_NEW_SUBSCRIPTIONS NUMBER(18,0),
    ROLLING_30_ACCOUNTS_WITH_NEW_SUBSCRIPTIONS NUMBER(18,0),
    ROLLING_30_NEW_ACCOUNTS NUMBER(18,0)
);

-- ========================================================================
-- TABLE 16: Net Churn
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_ENGAGEMENT.RETENTION.AGG_NET_CHURN_VIZ_MV (
    PREV_ACTIVE NUMBER(18,0),
    MONTH DATE,
    NET_CHURN NUMBER(18,6),
    CURR_NEW NUMBER(18,0),
    CURR_CHURN NUMBER(18,0),
    CURR_REACTIVE NUMBER(18,0),
    CURR_ACTIVE NUMBER(18,0),
    RETURN_RATE NUMBER(18,6),
    GROSS_CHURN_RATE NUMBER(18,6)
);

-- ========================================================================
-- TABLE 17: Monthly Churn Model Aggregate
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_ENGAGEMENT.RETENTION.AGG_MONTHLY_CHURN_MODEL_AGGREGATE_MV (
    CURR_REACTIVE NUMBER(18,0),
    PREV_ACTIVE NUMBER(18,0),
    CURR_CHURN NUMBER(18,0),
    MONTH DATE,
    MODEL VARCHAR(200),
    CURR_ACTIVE NUMBER(18,0),
    CHIP VARCHAR(100),
    SOC VARCHAR(50),
    CURR_NEW NUMBER(18,0)
);

-- ========================================================================
-- TABLE 18: Active Accounts Daily
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_ENGAGEMENT.KPIS.AGG_ACTIVE_ACCOUNTS_DAILY_FIN_COLLATED (
    ACTIVITY_DATE DATE,
    PROCESS_DATE DATE,
    ACTIVE_ACCOUNTS_VIZIO_30_DAYS NUMBER(18,0),
    ACTIVE_ACCOUNTS_ONN_30_DAYS NUMBER(18,0),
    TOTAL_ACTIVE_ACCOUNTS_30_DAYS NUMBER(18,0)
);

-- ========================================================================
-- TABLE 19: Monthly Actives
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_ENGAGEMENT.KPIS.AGG_QUARTERLYREPORT_MONTHLY_ACTIVES_MV (
    SCREENSIZE VARCHAR(20),
    TOTAL_TVS NUMBER(18,0),
    CHIPSET VARCHAR(100),
    SOURCE VARCHAR(200),
    MODEL_NAME VARCHAR(200),
    COVP VARCHAR(100),
    TIME_PERIOD VARCHAR(50),
    PROCESS_DATE DATE
);

-- ========================================================================
-- TABLE 20: Active Tokens Rolling 30 Days
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_ENGAGEMENT.KPIS.AGG_COUNT_ACTIVE_TOKENS_IOT_INSCAPE_COMBINED_ROLLING_30_DAYS_V1 (
    ACTIVITY_DATE DATE,
    UNIQUE_TOKEN_ROLLING_30_CNT NUMBER(18,0)
);

-- ========================================================================
-- TABLE 21: Impressions
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_MARKETING.HOMESCREEN.AGG_IMPRESSION_V2_MV (
    DL_CLIENTTYPE VARCHAR(100),
    ITEMTITLE VARCHAR(1000),
    DL_PAGE VARCHAR(200),
    LANDINGPAGEID VARCHAR(200),
    POSITION INTEGER,
    ROWPOSITION INTEGER,
    ITEMPOSITION INTEGER,
    DL_SECTIONNAME VARCHAR(500),
    AD_CAMPAIGN VARCHAR(500),
    CAMPAIGN_TYPE VARCHAR(100),
    IMPRESSION_TYPE VARCHAR(100),
    APP_ID VARCHAR(100),
    APP_NAMESPACE VARCHAR(200),
    PARTNER VARCHAR(500),
    SUBGROUP VARCHAR(200),
    ROW_TYPE VARCHAR(100),
    ITEM_TYPE VARCHAR(100),
    BUTTONEVENT VARCHAR(100),
    CONTENT_ID VARCHAR(200),
    OVERLAYPAGE VARCHAR(200),
    KEY VARCHAR(200),
    OEM_BRAND VARCHAR(100),
    NUM_OF_DEVICES NUMBER(18,0),
    NUM_OF_IMPRESSIONS NUMBER(18,0),
    NUM_OF_CLICKS NUMBER(18,0),
    NUM_OF_FOCUS NUMBER(18,0),
    NUM_OF_TIMEOUTS NUMBER(18,0),
    AUDIT_UPDATE_TS TIMESTAMP_NTZ,
    AUDIT_SOURCE VARCHAR(200),
    ACTIVITY_DATE DATE
);

-- ========================================================================
-- TABLE 22: Sports Engagement
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_MARKETING.SPORTS.AGG_SPORTS_ENGAGEMENT_SUMMARY (
    TIME_GRAIN VARCHAR(20),
    DATE DATE,
    PAGE VARCHAR(200),
    PAGE_TYPE VARCHAR(100),
    SECTION_NAME VARCHAR(500),
    CHIPSET VARCHAR(100),
    SIZE VARCHAR(20),
    HAS_VA_LINKED BOOLEAN,
    IMPRESSIONS NUMBER(18,0),
    FOCUSES NUMBER(18,0),
    CLICKS NUMBER(18,0),
    OEM_BRAND VARCHAR(100)
);

-- ========================================================================
-- TABLE 23: Push Notifications
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_MARKETING.BRAZE.AGG_BRAZE_PUSH_NOTIFICATION_TIME_GRAIN (
    TIME_GRAIN VARCHAR(20),
    PERIOD_START DATE,
    PERIOD_END DATE,
    TOTAL_PUSH_NOTIFICATIONS_SENT NUMBER(18,0),
    IOS_PUSH_NOTIFICATIONS_SENT NUMBER(18,0),
    ANDROID_PUSH_NOTIFICATIONS_SENT NUMBER(18,0),
    TOTAL_PUSH_NOTIFICATIONS_OPENED NUMBER(18,0),
    IOS_PUSH_NOTIFICATIONS_OPENED NUMBER(18,0),
    ANDROID_PUSH_NOTIFICATIONS_OPENED NUMBER(18,0)
);

-- ========================================================================
-- TABLE 24: Inscape Monthly Engagements
-- ========================================================================

CREATE OR REPLACE TABLE VIZIO_MARKETING.INSCAPE.INSCAPE_MONTHLY_ENGAGEMENTS (
    MONTH DATE,
    ENGAGEMENT_TYPE VARCHAR(100),
    ENGAGEMENT_COUNT NUMBER(18,0),
    UNIQUE_DEVICES NUMBER(18,0)
);

-- ========================================================================
-- GRANT PERMISSIONS TO PUBLIC FOR DEMO USE
-- ========================================================================

GRANT USAGE ON DATABASE VIZIO_STREAMING TO ROLE PUBLIC;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VIZIO_STREAMING TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN DATABASE VIZIO_STREAMING TO ROLE PUBLIC;

GRANT USAGE ON DATABASE VIZIO_DEVICES TO ROLE PUBLIC;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VIZIO_DEVICES TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN DATABASE VIZIO_DEVICES TO ROLE PUBLIC;

GRANT USAGE ON DATABASE VIZIO_REVENUE TO ROLE PUBLIC;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VIZIO_REVENUE TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN DATABASE VIZIO_REVENUE TO ROLE PUBLIC;

GRANT USAGE ON DATABASE VIZIO_ENGAGEMENT TO ROLE PUBLIC;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VIZIO_ENGAGEMENT TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN DATABASE VIZIO_ENGAGEMENT TO ROLE PUBLIC;

GRANT USAGE ON DATABASE VIZIO_MARKETING TO ROLE PUBLIC;
GRANT USAGE ON ALL SCHEMAS IN DATABASE VIZIO_MARKETING TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN DATABASE VIZIO_MARKETING TO ROLE PUBLIC;

-- ========================================================================
-- BASE TABLES SETUP COMPLETE
-- ========================================================================

SELECT 'Vizio base tables created successfully!' as status,
       'Databases: VIZIO_STREAMING, VIZIO_DEVICES, VIZIO_REVENUE, VIZIO_ENGAGEMENT, VIZIO_MARKETING' as databases,
       '24 tables created across 5 databases' as tables;
